// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xchnooutgckpgrcqanfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjaG5vb3V0Z2NrcGdyY3FhbmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDQ3MDQsImV4cCI6MjA2NDQyMDcwNH0.ij3PIjUWQtwTaTVhZkVjE2Jkow2D-OchCnO2BEm_hIM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);