// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyszttnunsowxesgkrsu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5c3p0dG51bnNvd3hlc2drcnN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDk3MzcsImV4cCI6MjA2MzMyNTczN30.-sOv9DyM4UVDbrz3rZT4mU6SOiG-Cbk67p5aZ0lmK2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);